# Generated by Django 4.1.4 on 2022-12-14 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(max_length=50, verbose_name='name')),
                ('catDesc', models.TextField(verbose_name='description')),
                ('catImg', models.ImageField(upload_to='product\\images\\category', verbose_name='Image')),
                ('catParent', models.ForeignKey(blank=True, limit_choices_to={'catParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='main category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdName', models.CharField(max_length=100, verbose_name='Product Name')),
                ('prdDesc', models.TextField(verbose_name='Description')),
                ('prdMainImage', models.ImageField(blank=True, null=True, upload_to='product\\images\\item', verbose_name='Image')),
                ('prdPrice', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('prdDiscountPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Discount Price')),
                ('prdCost', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Cost')),
                ('prdCreated', models.DateTimeField(verbose_name='Created Date')),
                ('prdSlug', models.SlugField(blank=True, null=True, verbose_name='Product Url')),
                ('prdIsNew', models.BooleanField(default=True, verbose_name='New Product')),
                ('prdIsBestSeller', models.BooleanField(default=False, verbose_name='Best Seller')),
                ('prdCat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdImage', models.ImageField(upload_to='product\\images\\item', verbose_name='Image')),
                ('prdIProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdAltProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='product.product', verbose_name='product')),
                ('prdAlternatives', models.ManyToManyField(related_name='alternative_products', to='product.product', verbose_name='Alternatives')),
            ],
            options={
                'verbose_name': 'Product Alternative',
                'verbose_name_plural': 'Product Alternatives',
            },
        ),
        migrations.CreateModel(
            name='Product_Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdAccProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_acc_product', to='product.product', verbose_name='product')),
                ('prdAccessory', models.ManyToManyField(related_name='accessory_products', to='product.product', verbose_name='Accessories')),
            ],
            options={
                'verbose_name': 'Product_Accessory',
                'verbose_name_plural': 'Product_Accessories',
            },
        ),
    ]
